//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBSPortal3.SR_ImageController {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SR_ImageController.WebService_ImageControllerSoap")]
    public interface WebService_ImageControllerSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveImage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SaveImage(string ImageURL, string ImagePath, string ImageName, string RefID, string RefType, string UserID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService_ImageControllerSoapChannel : SBSPortal3.SR_ImageController.WebService_ImageControllerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService_ImageControllerSoapClient : System.ServiceModel.ClientBase<SBSPortal3.SR_ImageController.WebService_ImageControllerSoap>, SBSPortal3.SR_ImageController.WebService_ImageControllerSoap {
        
        public WebService_ImageControllerSoapClient() {
        }
        
        public WebService_ImageControllerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService_ImageControllerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_ImageControllerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_ImageControllerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SaveImage(string ImageURL, string ImagePath, string ImageName, string RefID, string RefType, string UserID) {
            return base.Channel.SaveImage(ImageURL, ImagePath, ImageName, RefID, RefType, UserID);
        }
    }
}
