<?xml version="1.0" encoding="utf-8"?><Database Name="SS_NPTDC" Class="LINQ_SystemDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=SS_NPTDC;User ID=rgbdeveloper" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SS_NPTDC_APP_ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SYS_UserRoleView" Member="SYS_UserRoleViews">
    <Type Name="SYS_UserRoleView">
      <Column Name="RoleCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastAction" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedByCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RoleMenu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SYS_UserRoleMenuView" Member="SYS_UserRoleMenuViews">
    <Type Name="SYS_UserRoleMenuView">
      <Column Name="RoleMenuID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MenuID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="RoleCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MenuLabel" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MenuName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsNode" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IconClass" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NoteMenuID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MenuLinkPage" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MenuOnClick" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MenuSeq" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SYS_ProgramView" Member="SYS_ProgramViews">
    <Type Name="SYS_ProgramView">
      <Column Name="ProgramID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProgramCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProgramName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastAction" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedByCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SysLogView" Member="SysLogViews">
    <Type Name="SysLogView">
      <Column Name="SystemLogID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RecordID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LogDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LogBy" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SysLogItemView" Member="SysLogItemViews">
    <Type Name="SysLogItemView">
      <Column Name="SystemLogItemID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SystemLogID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FieldName" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="OldValue" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="NewValue" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SYS_Program" Member="SYS_Programs">
    <Type Name="SYS_Program">
      <Column Name="ProgramID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProgramCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProgramName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastAction" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SYS_UserRole" Member="SYS_UserRoles">
    <Type Name="SYS_UserRole">
      <Column Name="RoleID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastAction" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RoleMenu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SYS_UserRoleMenu" Member="SYS_UserRoleMenus">
    <Type Name="SYS_UserRoleMenu">
      <Column Name="RoleMenuID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MenuID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SYS_OrganizationView" Member="SYS_OrganizationViews">
    <Type Name="SYS_OrganizationView">
      <Column Name="OrgName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="OrgCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="JointDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ExpiryDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UserCount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OrgPlan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Remark1" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastAction" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OrgID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedByCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OrgType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InvoiceAccountName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InvoiceAccountNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Website" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Facebook" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="InvoiceType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PhoneNo" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="JoinCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SYS_OrganizationMenuGroupView" Member="SYS_OrganizationMenuGroupViews">
    <Type Name="SYS_OrganizationMenuGroupView">
      <Column Name="OrgMenuGroupID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MenuGroupID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OrgID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OrgName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MenuGroupName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="MenuGroupCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AllowCreate" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AllowUpdate" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AllowDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AllowView" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastAction" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifiedByCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SYS_OrganizationMenuGroup" Member="SYS_OrganizationMenuGroups">
    <Type Name="SYS_OrganizationMenuGroup">
      <Column Name="OrgMenuGroupID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MenuGroupID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OrgID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MenuGroupName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AllowCreate" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AllowUpdate" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AllowDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AllowView" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastAction" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SYS_Organization" Member="SYS_Organizations">
    <Type Name="SYS_Organization">
      <Column Name="OrgID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OrgName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="OrgCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OrgType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="JointDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ExpiryDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UserCount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OrgPlan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Remark1" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceAccountName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InvoiceAccountNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastAction" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Website" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Facebook" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="InvoiceType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PhoneNo" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="JoinCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SysLogItem" Member="SysLogItems">
    <Type Name="SysLogItem">
      <Column Name="SystemLogItemID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SystemLogID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FieldName" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="OldValue" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="NewValue" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SysLog" Member="SysLogs">
    <Type Name="SysLog">
      <Column Name="SystemLogID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RecordID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LogDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LogBy" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SysRunningNo" Member="SysRunningNos">
    <Type Name="SysRunningNo">
      <Column Name="RunningNoID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RunningNoCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RunningSequence" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RunningSequneceLength" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RunningPrefix" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RunningSequenceWord" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OrganizationID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OrganizationPrefix" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SYS_Menu" Member="SYS_Menus">
    <Type Name="SYS_Menu">
      <Column Name="MenuID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MenuName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MenuLabel" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="IsNode" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IconClass" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NoteMenuID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MenuLinkPage" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="MenuOnClick" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="MenuSeq" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastAction" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SYS_MenuView" Member="SYS_MenuViews">
    <Type Name="SYS_MenuView">
      <Column Name="MenuID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MenuName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MenuLabel" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="IsNode" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IconClass" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NoteMenuID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MenuLinkPage" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="MenuOnClick" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="MenuSeq" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastAction" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedByCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SYS_MenuGroupView" Member="SYS_MenuGroupViews">
    <Type Name="SYS_MenuGroupView">
      <Column Name="MenuGroupID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MenuGroupCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MenuGroupName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="MenuGroupSeq" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastAction" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OrgID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedByCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedByCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SYS_MenuGroup" Member="SYS_MenuGroups">
    <Type Name="SYS_MenuGroup">
      <Column Name="MenuGroupID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MenuGroupCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MenuGroupSeq" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MenuGroupName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastAction" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SYS_Config" Member="SYS_Configs">
    <Type Name="SYS_Config">
      <Column Name="ConfigID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DefaultEmailClient" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="DefaultEmailAddress" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="DefaultEmailPassword" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SYS_User" Member="SYS_Users">
    <Type Name="SYS_User">
      <Column Name="UserID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ContactInfo" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Ref_Type" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ref_ID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastLogin" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastAction" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OrgID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsLoggedIn" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PositionID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SYS_UserView" Member="SYS_UserViews">
    <Type Name="SYS_UserView">
      <Column Name="UserID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ContactInfo" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Ref_Type" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ref_ID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastLogin" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastAction" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedByCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RoleCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="RoleID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RoleMenu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="OrgName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="OrgID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OrgCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsLoggedIn" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OrgType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InvoiceType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DepartmentName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DepartmentID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PositionCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PositionName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PositionID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SYS_UserRoleProgram" Member="SYS_UserRolePrograms">
    <Type Name="SYS_UserRoleProgram">
      <Column Name="RoleProgramID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProgramID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AllowView" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AllowDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AllowUpdate" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AllowCreate" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Scope" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AllowDecision" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AllowAllDepartment" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SYS_UserRoleProgramView" Member="SYS_UserRoleProgramViews">
    <Type Name="SYS_UserRoleProgramView">
      <Column Name="RoleProgramID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProgramID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AllowView" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AllowDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AllowUpdate" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AllowCreate" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Scope" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProgramCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProgramName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="RoleCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AllowDecision" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AllowAllDepartment" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.SYS_GetOrganizationMenuGroup" Method="SYS_GetOrganizationMenuGroup">
    <Parameter Name="orgid" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="SYS_GetOrganizationMenuGroupResult">
      <Column Name="OrgID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OrgMenuGroupID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MenuGroupID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MenuGroupCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MenuGroupName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="AllowCreate" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AllowUpdate" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AllowDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AllowView" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SYS_GetMenuRole" Method="SYS_GetMenuRole">
    <Parameter Name="roleid" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="SYS_GetMenuRoleResult">
      <Column Name="RoleID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RoleMenuID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MenuID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MenuName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MenuLabel" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Sys_Do_Login" Method="Sys_Do_Login">
    <Parameter Name="usercode" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="password" Type="System.String" DbType="NVarChar(200)" />
    <ElementType Name="Sys_Do_LoginResult">
      <Column Name="UserID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ref_ID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ref_Type" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="RoleMenu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SYS_GetProgramRole" Method="SYS_GetProgramRole">
    <Parameter Name="roleid" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="SYS_GetProgramRoleResult">
      <Column Name="RoleID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RoleProgramID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProgramID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProgramName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ProgramCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AllowCreate" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AllowUpdate" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AllowDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AllowView" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AllowDecision" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AllowAllDepartment" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>